### ISSUE TITLE
Buttons broken in latest webcall server version?

### ISSUE THREAD

**Issue by pilotseye** [mehrvarz/webcall#14]
I implemented a call button for testing purposes on one of my webpages and it worked fine, but in recent updates of the webcall server it seems to be broken, see console output by Chrome browser:
`Uncaught TypeError: Cannot read properties of null (reading 'contentWindow')
    at window.onload (button.js:3:3)
window.onload @ button.js:3
load (async)
(anonymous) @ button.js:1
`
and
`Uncaught TypeError: Cannot set properties of null (setting 'value')
    at caller.js:642:27
    at caller.js:1120:4
    at xhr.onreadystatechange (client.js:315:4)
(anonymous) @ caller.js:642
(anonymous) @ caller.js:1120
xhr.onreadystatechange @ client.js:315
XMLHttpRequest.send (async)
ajaxFetch @ client.js:341
checkServerMode @ caller.js:1118
onload2 @ caller.js:630
window.onload @ caller.js:521
load (async)
(anonymous) @ caller.js:115`

it does not matter if I enter the ID or nickname, the error remains the same.
Did the button behaviour change in any way different to the documentation maybe?

Thanks!

**Comment by mehrvarz** [comment]
The issue should be solved now. However, the functionality may get dropped in future releases. Decision pending.

**Comment by pilotseye** [comment]
Thanks for your feedback, it seems that the button is still not loading though, also sorry to hear that you will drop this feature maybe in the future. Are you thinking of an alternative way how to connect to clients as simple as webpage with an integrated button?

**Comment by mehrvarz** [comment]
> it seems that the button is still not loading though

Does it fail in the same way as before? In a different way?
It seems to work for me on [this page](https://timur.mobi/webcall/callbutton/callcenter-demo/).

> also sorry to hear that you will drop this feature maybe in the future. Are you thinking of an alternative way how to connect to clients as simple as webpage with an integrated button?

I am unable to say at this moment.

**Comment by pilotseye** [comment]
I got it working again using the server 3.0.3 executable and update nginx config - guess I will wait for 3.2.11 executable to become available then.

**Comment by mehrvarz** [comment]
Fix will come with 3.2.12 in a few days.

**Comment by mehrvarz** [comment]
Took a bit longer but is now released. If it works for you, please close this issue. Thank you

**Comment by gnusupport** [comment]
How do I upgrade on server? git pull?

**Comment by gnusupport** [comment]
I have re-built it, I will check now.
